### ISSUE TITLE
exchange experiences? overlapping tool :-D

### ISSUE THREAD

**Issue by juleskers** [lindenb/igvfox#1]
Dear Pierre,

I came across this firefox plugin while browsing the "IGV" tag.
It seems you were scratching the same itch I was with this: controlling IGV from the browser, to make large projects more manageable. I'd love to exchange experiences with you! (If you're not interested, I won't be offended, I see this has been dormant since 2014, so maybe you have moved on to new things? feel free to close without comment!)

I just now released my own in-house work to control IGV: https://github.com/eilslabs/igv-crawler
(I don't do browsing to locations like your example, just opening files from our central storage)

Some random questions:
- Are you still using this plugin?
   - if so, what do you think about firefox's new webextensions API?
- Why did you choose to use javascript+extension, instead of direct URLs to localhost?
- Are there things you'd do differently today? (So that I may avoid suboptimal solutions myself)
- Anything you'd like to know from me / my project?

Kind Regards,
Jules Kerssemakers,
DKFZ Heidelberg, Germany

**Comment by lindenb** [comment]
Hi
> Are you still using this plugin? 

no IGV can be controlled using a simple URL,  I don't need this anymore

> if so, what do you think about firefox's new webextensions API?

I haven't tested it.

> Why did you choose to use javascript+extension, instead of direct URLs to localhost?

see previous :-)

Best,
P.
